version: '3.2'

services:
  server:
    build: .
    restart: unless-stopped
  caddy:
    image: caddy:2
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - server
