name: test-environment
on:
  push:
    branches:
      - main
    paths:
      - 'docker/Dockerfile.mlflow'
      - 'Makefile'
      - '.github/workflows/mlflow-environment.yml'


jobs:
  documentation:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build Docker
      run: |
        make mlflow-build
    - name: Deploy on ECR
      run: |
        make mlflow-deploy
